[project]
name = "qes-embedding"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "zhoudd3", email = "zhoudd3@lenovo.com" }
]
requires-python = ">=3.12"
dependencies = [
    "langchain-milvus>=0.2.1",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
