[project]
name = "qes-openai-client"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "zhoudd3", email = "zhoudd3@lenovo.com" }
]
requires-python = ">=3.12"
dependencies = [
    "openai>=1.100.1",
    "qes-utils",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv.sources]
qes-utils = { workspace = true }
